### ISSUE TITLE
[owners] Transition from YAML as owners file format

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amp-github-apps#442]
YAML is tricky to write and inconsistent to parse, which can cause problems as contributors try to write owners rules. Some things need to be quoted, some don't, lists and dicts can be defined in many ways, and it's generally less familiar to people than JSON.

Plan:
- [x] Add support for parsing OWNERS.____; prefer the YAML form when present
- [x] Create script to take the parsed form of an OWNERS.yaml file and output the matching OWNERS.____
- [x] Generate & submit OWNERS.____ for all OWNERS.yaml files in `amphtml`
- [x] Remove all OWNERS.yaml files
- [ ] Remove support for YAML

/cc @kristoferbaxter

**Comment by danielrozenberg** [comment]
JSON is hard for humans to write and read... How about protoascii? :D

**Comment by rcebulko** [comment]
That seems like a good option, since contributors will likely be familiar with it anyway

**Comment by mrjoro** [comment]
protoascii sounds good to me!

JSON also has the issue that it doesn't allow comments, which are sometimes useful in the files.

**Comment by rsimha** [comment]
After chatting off line with @rcebulko, I too am in favor of protoascii.

**Comment by rcebulko** [comment]
Example: current root OWNERS.yaml

```yaml
# For an explanation of the OWNERS.yaml rules and syntax, see:
# https://github.com/ampproject/amp-github-apps/blob/master/owners/OWNERS.example.yaml

- "?cramforce"
- "?dvoytenko"
- "?jridgewell"
- "**/validator-*.{protoascii,html,out}": "#ampproject/wg-caching"
- "*.md": ampproject/wg-outreach
- "{.*,{{babel,bundles}.config,gulpfile}.js,renovate.json}": ampproject/wg-infra
- "{package.json,yarn.lock}":
  - ampproject/wg-infra
  - ampproject/wg-runtime
  - ampproject/wg-performance

# TODO(#24685): Remove this once most owners files have been update and/or the
# Travis check is implemented.
- "**/OWNERS.yaml": "#rcebulko"
```

```protobuf
// For an explanation of the OWNERS.yaml rules and syntax, see:
// https://github.com/ampproject/amp-github-apps/blob/master/owners/OWNERS.example.yaml

rules: {
  owners: {
    name: "cramforce"
    notify: NEVER
  }
  owners: {
    name: "dvoytenko"
    notify: NEVER
  }
  owners: {
    name: "jridgewell"
    notify: NEVER
  }
}

rules: {
  pattern: "**/validator-*.{protoascii,html,out}"
  owners: {
    // The validator team should be made aware of all changes to validator files.
    name: "ampproject/wg-caching"
    notify: ALWAYS
  }
}

rules: {
  pattern: "*.md"
  owners: { name: "ampproject/wg-outreach" }
}

rules: {
  pattern: "{.*,{{babel,bundles}.config,gulpfile}.js,renovate.json}"
  owners: { name: "ampproject/wg-infra" }
}

rules: {
  pattern: "{package.json,yarn.lock}"
  owners: { name: "ampproject/wg-infra" }
  owners: { name: "ampproject/wg-runtime" }
  owners: { name: "ampproject/wg-performance" }
}

// TODO(#24685): Remove this once most owners files have been update and/or the
// Travis check is implemented.
rules: {
  pattern: "**/OWNERS.yaml"
  owners: {
    name: "rcebulko"
    notify: ALWAYS
  }
}
```

**Comment by rcebulko** [comment]
The protobuf message definitions would look like:

```protobuf
enum NotificationControl {
  NONE = 0;
  NEVER = 1;
  ALWAYS = 2;
}

message Owner {
  // Case-insensitive team name or username
  // ex. `ampproject/wg-infra`, `rcebulko`
  required string name = 1;
  optional NotificationControl notify = 2;
}

message Rule {
  repeated Owner owners = 1;
  optional string pattern = 2;
}

message OwnersFile {
  repeated Rule rules = 1;
}
```

**Comment by rsimha** [comment]
Thanks for the clarifying example. Does the protoascii format allow for all the separate sections to be combined into one top-level `rules` section containing multiple `owners` (+ `pattern` + `notify`)  sections?

**Comment by rcebulko** [comment]
I believe the protobuf syntax requires using the key for each instance of a repeated field. For example, [this amp-bind validator file](https://github.com/ampproject/amphtml/blob/master/extensions/amp-bind/validator-amp-bind.protoascii) shows how repeated fields like `tags` and `attrs` are used.

**Comment by rcebulko** [comment]
Which, while protoascii is the most explicit/well-defined syntax, it's also the most verbose

**Comment by rcebulko** [comment]
For comparison, the JSON format (fudging the standard a bit to be more JavaScript-like, supporting comments, non-quoted keys, and trailing commas) would look like:

```javascript
// For an explanation of the OWNERS.yaml rules and syntax, see:
// https://github.com/ampproject/amp-github-apps/blob/master/owners/OWNERS.example.yaml

{
  rules: [
    {
      owners: [{
        name: "cramforce",
        notify: "NEVER",
      }, {
        name: "dvoytenko",
        notify: "NEVER",
      }, {
        name: "jridgewell",
        notify: "NEVER",
      }]
    },

    {
      pattern: "**/validator-*.{protoascii,html,out}",
      owners: [{
        // The validator team should be made aware of all changes to validator files.
        name: "ampproject/wg-caching",
        notify: "ALWAYS",
      }]
    }, 
    
    {
      pattern: "*.md",
      owners: [{ name: "ampproject/wg-outreach" }],
    },

    {
      pattern: "{.*,{{babel,bundles}.config,gulpfile}.js,renovate.json}",
      owners: [{ name: "ampproject/wg-infra" }],
    },

    {
      pattern: "{package.json,yarn.lock}",
      owners: [
        { name: "ampproject/wg-infra" },
        { name: "ampproject/wg-runtime" },
        { name: "ampproject/wg-performance" },
      ],
    }

    {
      // TODO("24685): Remove this once most owners files have been update and/or the
      // Travis check is implemented.
      pattern: "**/OWNERS.yaml",
      owners: [{
        name: "rcebulko",
        notify: "ALWAYS",
      }],
    },
  ]
}
```

**Comment by rcebulko** [comment]
@rsimha @danielrozenberg 
Update: looks like there is no existing support for parsing the text format of protocal buffers in JavaScript (only the wire format byte array which is, ah, less than human-readable). So, now leaning back toward JavaScript rather than relying on something like Python as a go-between just to parse protoascii/pbtxt files

**Comment by rcebulko** [comment]
@mrjoro please confirm the JSON approach looks good to you if you have a moment

**Comment by mrjoro** [comment]
My main concern is that this format is JSON-like, but isn't actual JSON right (for the reasons you mentioned).  I suppose we could just call it a JS format instead of JSON format and be good?

**Comment by rcebulko** [comment]
I think what we're really looking for is [JSON5](https://json5.org), which is a superset of JSON designed to be more human-readable and -writable. Notably, it supports comments, unquoted keys, single-quotes, and trailing commas.

**Comment by rcebulko** [comment]
For that reason, I'm curious @mrjoro @rsimha if you think we should have our owners files be:
- `OWNERS.js` since that will trigger correct syntax highlighting in editors (but maybe that would get built/trigger Travis or other side-effects since it's `*.js?`
- `OWNERS.json` since that's approximately correct and familiar, but may result in incorrect syntax highlighting
- `OWNERS.json5` which is technically accurate but would result in no syntax highlighting at all
- `OWNERS` without any file extension so that the extension/syntax highlighting can't introduce confusion and developers will work off of existing correct example files

I'd lean toward the first or last options.

**Comment by mrjoro** [comment]
OK, I think that's fine then. :)  I have no strong opinion on the filename, so I'll leave that up to y'all.

**Comment by rsimha** [comment]
The last file name of just `OWNERS` will give us maximum flexibility, while preventing the need for file extension based exceptions to be made across the build system.

**Comment by rcebulko** [comment]
Conversion script: https://gist.github.com/rcebulko/1bdc4086f8bf3e97a3119d0d9b7cf95e

**Comment by rcebulko** [comment]
[accidentally closed]
